# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
#  - release
#  - nightly
  - "0.5"
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SoftConfidenceWeighted"); Pkg.test("SoftConfidenceWeighted"; coverage=true)'
